name: flutter_leielyq_plugin
description: A new leielyq Flutter plugin.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #  banner_view:
  #    git: https://github.com/yangxiaoweihn/BannerView.git
  dio: 2.2.2
  dio_http_cache: ^0.1.4
  extended_image: ^0.7.2
#  extended_image_library: 0.1.8
  font_awesome_flutter: 8.0.1
#  flutter_boost:
#    git:
#      url: https://github.com/alibaba/flutter_boost.git
#      ref: feature/base_flutter_1.12_upgrade
  flutter_screenutil: 0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: false
    androidPackage: com.leielyq.flutter_module_01
    iosBundleIdentifier: com.leielyq.flutterModule01

